version: "3.4"
services:
  dev-postgres:
    image: postgres:12.4
    container_name: dev-postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    command: "postgres -c log_statement=all -c log_duration=on -c log_min_duration_statement=-1"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "$DEV_CONTAINERS_HOME/dev-postgres:/var/lib/postgresql/data"
    healthcheck:
      test: pg_isready -U postgres || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
