version: "3.4"
services:
  dev-rabbit:
    image: rabbitmq:3.8.5-management
    container_name: dev-rabbit
    expose:
      - 15672
      - 5672
    ports:
      - 15672:15672
      - 5672:5672
    hostname: "dev-rabbit"
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 1024MiB
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - "$DEV_CONTAINERS_HOME/dev-rabbit:/var/lib/rabbitmq"
    healthcheck:
      test: rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 30s
      timeout: 15s
      retries: 2
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
