version: "3.4"
services:
  dev-openzipkin:
    image: openzipkin/zipkin:2.21.7
    container_name: dev-openzipkin
    expose:
      - 9411
    ports:
      - 9411:9411
    # We will use the inmemory approach for local development but if we really want the storage we can use elasticsearch
    # environment:
    #   - "STORAGE_TYPE=elasticsearch"
    #   - "ES_HOSTS=http://dev-elasticsearch:9200"
    healthcheck:
      test:  wget -qO- http://localhost:9411/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
# # If we use storage then we will need to run also the openzipkin/zipkin-dependencies container on a scheduler to build the dependency graph data
#   dev-openzipkin-dependencies:
#     image: openzipkin/zipkin-dependencies:2.4.4
#     container_name: dev-openzipkin-dependencies
#     environment:
#       STORAGE_TYPE: elasticsearch
#       ES_HOSTS: http://dev-elasticsearch:9200
#       JAVA_OPTS: -Xmx512m -Xms128m #This might not work as expected. Then again, maybe it does. Kind of hard to determine
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "100m"
#         max-file: "5"