version: "3.4"
services:
  dev-elasticsearch:
    image: elasticsearch:7.9.3
    container_name: dev-elasticsearch
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=dev-elasticsearch
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/backups
      # Disable memory swapping
      - bootstrap.memory_lock=true
      # The value for these setting depends on the amount of RAM available on your server. Good rules of thumb are:
      # Set the minimum heap size (Xms) and maximum heap size (Xmx) to be equal to each other.
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
      - "ES_JAVA_OPTS=-Xms256m -Xmx1g"
      - "ES_HEAP_SIZE=512m"
    volumes:
      - "$DEV_CONTAINERS_HOME/dev-elasticsearch/es-data:/usr/share/elasticsearch/data"
      - "$DEV_CONTAINERS_HOME/dev-elasticsearch/es-backups:/usr/share/elasticsearch/backups"
    ulimits:
      # From: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-prod-cluster-composefile
      memlock:
        soft: -1
        hard: -1
      nofile:
        # From: https://www.elastic.co/guide/en/elasticsearch/reference/current/file-descriptors.html
        soft: 65536
        hard: 65536
    healthcheck:
      test:  curl --fail --silent http://127.0.0.1:9200/_cluster/health?wait_for_status=yellow&timeout=13s || exit 1
      interval: 30s
      timeout: 15s
      retries: 2
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
